metrics:
  global:
    scrape_interval: ${SCRAPE_INTERVAL:-15s}
  configs:
    - name: hosted-prometheus
      scrape_configs:
        - job_name: node
          static_configs:
            - targets: ['${TARGET_HOST:-localhost:9779}']
          metric_relabel_configs:
            - source_labels: []
              target_label: environment
              replacement: ${ENVIRONMENT:-dev}

      remote_write:
        - url: ${REMOTE_WRITE_URL}
          basic_auth:
            username: ${REMOTE_WRITE_USERNAME}
            password: ${REMOTE_WRITE_PASSWORD}
