metrics:
  global:
    scrape_interval: 5s
  configs:
    - name: hosted-prometheus
      scrape_configs:
        - job_name: node
          static_configs:
            - targets: ['${TARGET_HOST:-localhost:9779}']
      remote_write:
        - url: ${REMOTE_WRITE_URL}
          basic_auth:
            username: ${REMOTE_WRITE_USERNAME}
            password: ${REMOTE_WRITE_PASSWORD}
