name: E2E tests

on:
  push:
    branches: ['*']

env:
  DOCKERHUB_REPOSITORY: 'defcon007/ecs-prometheus-exporter'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha,scope=prod
          cache-to: type=gha,scope=prod,mode=max
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.GITHUB_REF_NAME_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

  E2E-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start Mockoon server for mock ECS metadata
        run: |
          docker run --network host -v ${{ github.workspace }}/mockoon-ecs-metadata-sample-response.json:/data/mockoon.json -d mockoon/cli  --data /data/mockoon.json --port 3001

      - name: Run Docker image
        run: docker run --name ecs-exporter --network host --env-file ${{ github.workspace }}/test/e2e-env-file -d ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.GITHUB_REF_NAME_SLUG }}

      - name: Wait for Docker image to start
        run: sleep 5

      - name: Run k6 test
        run: |
          docker run --network host -v ${{ github.workspace }}/test/k6-test.js:/data/script.js grafana/k6:latest run /data/script.js
